/* ============================================================================
   Build the itch.io upload.

   itch.io serves a project from STATIC HOSTING: a ZIP with an index.html at its
   root, or a single .html file. It has no backend, so only the offline build can
   go there - Entrepreneurs.html, which plays solo against bots and holds the
   whole game in one file. online.html needs server.js and cannot work.

   THAT IS NOT A DOWNGRADE, IT IS THE FUNNEL. A stranger will not make an account
   to try an unknown economic game. They will click a thing that starts playing.
   So itch gets the solo game, and the page points at the online site for anyone
   who wants to play people.

   WHAT THIS EMITS, into dist/:

     entrepreneurs-itch.zip   index.html, nothing else. Upload this.
     itch-page.md             the page copy - description, tags, embed settings.

   The game already degrades correctly with no server behind it: useFeedbackAccess
   fetches /api/account, that 404s, and it sets server:false, which hides the
   feedback box and the records page. Three requests fail in the console and
   nothing else notices. Verified in a real browser at six viewport sizes with no
   server running: no JavaScript errors, no horizontal scroll, board renders.

   EMBED SIZE MATTERS AND THE DEFAULT IS WRONG. itch defaults to 640x360. This
   game's layout switches to its side-by-side desktop form at 1152px wide; below
   that everything stacks into a column about 3000px tall, which works but is a
   miserable way to meet it. 1280x900 fits the board with the tutorial open.

   Run: node make_itch.mjs
   ========================================================================== */
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from "fs";
import { execFileSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "Entrepreneurs.html");
const DIST = path.join(HERE, "dist");

if (!existsSync(SRC)) {
  console.error("Entrepreneurs.html is missing - run `node build.mjs` first.");
  process.exit(1);
}

/* The offline build must not have picked up anything it cannot reach from a
   static host. A CDN link or a stylesheet URL would work here and fail for a
   player behind a strict network, so it is worth one check rather than a bug
   report from a stranger who will not send one. */
const html = readFileSync(SRC, "utf8");
const external = [...html.matchAll(/(?:src|href)="(https?:\/\/[^"]+)"/g)].map((m) => m[1]);
if (external.length) {
  console.error("the offline build references external URLs, which itch cannot guarantee:");
  external.slice(0, 10).forEach((u) => console.error("   " + u));
  process.exit(1);
}

mkdirSync(DIST, { recursive: true });
const indexPath = path.join(DIST, "index.html");
writeFileSync(indexPath, html);

const zipPath = path.join(DIST, "entrepreneurs-itch.zip");
try {
  execFileSync("zip", ["-qj", zipPath, indexPath], { cwd: DIST });
} catch (e) {
  console.error("could not run `zip` - upload dist/index.html directly instead, "
    + "itch accepts a single .html file.");
}

const kb = (p) => `${Math.round(statSync(p).size / 1024)} kB`;
console.log(`dist/index.html              ${kb(indexPath)}`);
if (existsSync(zipPath)) console.log(`dist/entrepreneurs-itch.zip  ${kb(zipPath)}`);

/* ---------------------------------------------------------------- page copy */
const PAGE = `# itch.io page copy

Generated by make_itch.mjs. Everything below is ready to paste.

## Upload

\`dist/entrepreneurs-itch.zip\` (contains index.html). itch also accepts
\`dist/index.html\` on its own.

## Embed options  — the defaults are wrong for this game

| setting | value | why |
|---|---|---|
| Embed in page | yes | it is one HTML file, nothing to download |
| Viewport | **1280 x 900** | the layout goes side-by-side at 1152px wide; below that it stacks into a ~3000px column |
| Mobile friendly | **off** | it runs on a phone but it is an information-dense board game; it reads badly |
| Automatically start on page load | on | it is a small single file, there is no long load to defer |
| Fullscreen button | **on** | the board is worth the whole screen |
| Enable scrollbars | on | the page runs a little taller than the frame in some states |
| SharedArrayBuffer | off | not used |

## Title

Entrepreneurs

## Short description (the one-liner under the title)

A medium-heavy economic euro: build companies in a 4x4 city, pay your rivals'
supply chains, and move the market every time you build.

## Description

**Entrepreneurs** is a medium-heavy economic game for 2-6 players. This is the
solo version: you against up to five bots, the full twelve-quarter game, no
account, no download, nothing to install.

Every company you build pays its operating costs to companies in *other*
industries - your rivals' companies. That is the heart of it. Building pushes
your own industry's price down and every supplier you now buy from up, so the
market is the sum of what everyone at the table has built, and it moves under
you while you plan.

Six industries, and they are genuinely different. Retail and Hospitality open
cheaply, but Hospitality's running costs are punishing where Retail's are
moderate. Utilities and Retail both run on high volume and low prices - and they
grow in opposite directions: Utilities spreads horizontally across the ground as
it scales, while Retail stacks vertically and reaches a number of districts equal
to its level. What you can profitably build depends on what is already standing.

- 2-6 players, 12 quarters over 3 fiscal years
- 120-180 minutes at a physical table
- Full rulebook built in, searchable, in English, Portuguese and Simplified Chinese
- A ten-step tutorial that points at the thing it is describing

**Want to play against people?** The online version with real opponents is at
[entrepreneurs.boardgame](https://entrepreneurs.boardgame) - same game, same
rules, real tables.

## Tags

board game, economic, strategy, simulation, euro game, city builder, singleplayer,
turn-based, tabletop, management

## Genre

Strategy. (Simulation is the second-best fit. "Educational" is the wrong shelf -
it puts the game next to maths drills rather than next to other euros.)

## Classification / other fields

- Kind: HTML
- Release status: Released (or Prototype, if you want the feedback framing)
- Average session: A few hours
- Inputs: Mouse, Touchscreen
- Accessibility: has subtitles? no. Colour: every industry has a letter code and
  a glyph as well as a colour, so it is playable in greyscale.

## What to say in the devlog / first post

Be specific about the one mechanism that is unusual, not about the theme. The
hook is: *your operating costs are paid to other players' companies, so the
market moves every time anybody builds.* That is the sentence that makes someone
try it.
`;

const pagePath = path.join(DIST, "itch-page.md");
writeFileSync(pagePath, PAGE);
console.log(`dist/itch-page.md            ${kb(pagePath)}`);
console.log("\nUpload the zip, then set the embed size to 1280x900 - the itch default of");
console.log("640x360 puts this game in a column three thousand pixels tall.");
