/* ============================================================================
   Build the itch.io upload.

   itch.io serves a project from STATIC HOSTING: a ZIP with an index.html at its
   root, or a single .html file. It has no backend, so only the offline build can
   go there - Entrepreneurs.html, which plays solo against bots and holds the
   whole game in one file. online.html needs server.js and cannot work.

   THAT IS NOT A DOWNGRADE, IT IS THE FUNNEL. A stranger will not make an account
   to try an unknown economic game. They will click a thing that starts playing.
   So itch gets the solo game, and the page points at the online site for anyone
   who wants to play people.

   WHAT THIS EMITS, into dist/:

     entrepreneurs-itch.zip   index.html, nothing else. Upload this.
     itch-page.md             the page copy - description, tags, embed settings.

   The game already degrades correctly with no server behind it: useFeedbackAccess
   fetches /api/account, that 404s, and it sets server:false, which hides the
   feedback box and the records page. Three requests fail in the console and
   nothing else notices. Verified in a real browser at six viewport sizes with no
   server running: no JavaScript errors, no horizontal scroll, board renders.

   EMBED SIZE MATTERS AND THE DEFAULT IS WRONG. itch defaults to 640x360. This
   game's layout switches to its side-by-side desktop form at 1152px wide; below
   that everything stacks into a column about 3000px tall, which works but is a
   miserable way to meet it. 1280x900 fits the board with the tutorial open.

   Run: node make_itch.mjs
   ========================================================================== */
import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from "fs";
import { execFileSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "Entrepreneurs.html");
const DIST = path.join(HERE, "dist");

if (!existsSync(SRC)) {
  console.error("Entrepreneurs.html is missing - run `node build.mjs` first.");
  process.exit(1);
}

/* The offline build must not have picked up anything it cannot reach from a
   static host. A CDN link or a stylesheet URL would work here and fail for a
   player behind a strict network, so it is worth one check rather than a bug
   report from a stranger who will not send one. */
const html = readFileSync(SRC, "utf8");
const external = [...html.matchAll(/(?:src|href)="(https?:\/\/[^"]+)"/g)].map((m) => m[1]);
if (external.length) {
  console.error("the offline build references external URLs, which itch cannot guarantee:");
  external.slice(0, 10).forEach((u) => console.error("   " + u));
  process.exit(1);
}

/* WHICH BUILD IS ON THE SITE? The offline bundle does not contain ENGINE_VERSION -
   nothing in the single-player path reads it, so esbuild drops it - which means a
   stale upload is invisible from outside. It happened: the first zip handed over was
   built one rules version before the land award changed, and neither the page nor the
   file could say so.

   So stamp it. The comment is the first thing in the file, so `view-source:` on the
   live embed answers "is this current?" without downloading anything, and the page
   copy carries the same string to compare against. */
const engineVersion = (readFileSync(path.join(HERE, "EntrepreneursGame.jsx"), "utf8")
  .match(/const ENGINE_VERSION = "([0-9a-f]+)"/) || [])[1];
if (!engineVersion) {
  console.error("could not read ENGINE_VERSION from EntrepreneursGame.jsx - update this script.");
  process.exit(1);
}
const builtAt = new Date().toISOString().slice(0, 16).replace("T", " ") + "Z";
const stamp = `<!-- Entrepreneurs - offline build - rules engine ${engineVersion} - built ${builtAt} -->\n`;

mkdirSync(DIST, { recursive: true });
const indexPath = path.join(DIST, "index.html");
writeFileSync(indexPath, stamp + html);

const zipPath = path.join(DIST, "entrepreneurs-itch.zip");
try {
  execFileSync("zip", ["-qj", zipPath, indexPath], { cwd: DIST });
} catch (e) {
  console.error("could not run `zip` - upload dist/index.html directly instead, "
    + "itch accepts a single .html file.");
}

const kb = (p) => `${Math.round(statSync(p).size / 1024)} kB`;
console.log(`dist/index.html              ${kb(indexPath)}`);
if (existsSync(zipPath)) console.log(`dist/entrepreneurs-itch.zip  ${kb(zipPath)}`);

/* ---------------------------------------------------------------- page copy */
const PAGE = `# itch.io page copy

Generated by make_itch.mjs from rules engine **${engineVersion}**, built ${builtAt}.

To check whether the live page is still on this build, open \`view-source:\` on the
embed and read the first line - it carries the same engine id. A game deployed since
this was built is a DIFFERENT GAME to whoever plays it here, which matters most when
the page is being used to teach the rules.

Everything below is ready to paste.

## Upload

\`dist/entrepreneurs-itch.zip\` (contains index.html). itch also accepts
\`dist/index.html\` on its own.

## Embed options  — the defaults are wrong for this game

| setting | value | why |
|---|---|---|
| Embed in page | yes | it is one HTML file, nothing to download |
| Viewport | **1280 x 900** | the layout goes side-by-side at 1152px wide; below that it stacks into a ~3000px column |
| Mobile friendly | **off** | it runs on a phone but it is an information-dense board game; it reads badly |
| Automatically start on page load | on | it is a small single file, there is no long load to defer |
| Fullscreen button | **on** | the board is worth the whole screen |
| Enable scrollbars | on | the page runs a little taller than the frame in some states |
| SharedArrayBuffer | off | not used |

## Title

Entrepreneurs

## Short description (the one-liner under the title)

A heavy economic euro where your customers are your competitors: every company
you build buys from the table and sells to it at the same time.

## Description

**Your customers are your competitors.**

That is the whole game. Every company you build pays a supplier bill each
quarter, and that money does not vanish into the bank - it goes into the pots of
the industries its Blueprint buys from, and each pot is split among whoever owns
companies there. Usually the people you are trying to beat. Their companies buy
from yours in the same breath. The supply chain closes a loop, so no industry is
ever a dead end, and the table is your market and your rivals at once.

There are two economies running on top of each other. Your production sells to
the demand icons around you - that is the city, and it is a race, because the
icons are contested and first come first served. Your operating costs sell to
the table - that is the pots, and it rewards being somewhere nobody else is. The
industry nobody builds quietly collects everyone's money while its price climbs.

Building moves the market too: your own industry's price goes DOWN a dollar and
every supplier you now buy from goes UP one. So the market is the sum of what
everyone has built, and it shifts under you while you plan.

Six industries, and they are genuinely different. Retail and Hospitality are the
two cheapest ways in at $10 for a level-1 card, but they are opposite businesses:
Retail makes four units to sell at $4, Hospitality makes three at $5 and pays a
dollar more to run. Utilities and Retail are the high-volume, low-price pair -
and they grow in opposite directions, Utilities spreading horizontally across the
ground as it scales while Retail stacks vertically and reaches one more district
per level. Technology and Healthcare invert the whole thing: two units at $6,
with the heaviest running costs on the board. What is worth building depends
entirely on what is already standing.

- 2-6 players, 12 quarters over 3 fiscal years
- 120-180 minutes at a physical table
- Full rulebook built in and searchable, in English, Portuguese and Simplified Chinese
- A ten-step tutorial that points at the thing it is describing

**Hit fullscreen.** This one wants the room - the board, your ledger and the
industry pots all want to be on screen at once.

**Want to play against people?** The online version with real opponents is at
[entrepreneurs.boardgame](https://entrepreneurs.boardgame) - same game, same
rules, real tables.

## Tags

board game, economic, strategy, simulation, euro game, city builder, singleplayer,
turn-based, tabletop, management

## Genre

Strategy. (Simulation is the second-best fit. "Educational" is the wrong shelf -
it puts the game next to maths drills rather than next to other euros.)

## Classification / other fields

- Kind: HTML
- Release status: Released (or Prototype, if you want the feedback framing)
- Average session: A few hours
- Inputs: Mouse, Touchscreen
- Accessibility: has subtitles? no. Colour: every industry has a letter code and
  a glyph as well as a colour, so it is playable in greyscale.

## What to say in the devlog / first post

Be specific about the one mechanism that is unusual, not about the theme. The
hook is: *your customers are your competitors - every company buys from the table
and sells to it at once.* That is the sentence that makes someone try it, and it
is the counterintuitive direction that does the work: people expect the players
they are beating to be separate from the people paying them.
`;

const pagePath = path.join(DIST, "itch-page.md");
writeFileSync(pagePath, PAGE);
console.log(`dist/itch-page.md            ${kb(pagePath)}`);
console.log(`\nrules engine ${engineVersion}, built ${builtAt}`);
console.log("\nUpload the zip, then set the embed size to 1280x900 - the itch default of");
console.log("640x360 puts this game in a column three thousand pixels tall.");
